// source: HistoryList.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var ProductList_pb = require('./ProductList_pb.js');
goog.object.extend(proto, ProductList_pb);
var CartList_pb = require('./CartList_pb.js');
goog.object.extend(proto, CartList_pb);
goog.exportSymbol('proto.HistoryList', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.HistoryList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.HistoryList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.HistoryList.displayName = 'proto.HistoryList';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.HistoryList.prototype.toObject = function(opt_includeInstance) {
  return proto.HistoryList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.HistoryList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.HistoryList.toObject = function(includeInstance, msg) {
  var f, obj = {
    products: (f = msg.getProducts()) && ProductList_pb.ProductList.toObject(includeInstance, f),
    carts: (f = msg.getCarts()) && CartList_pb.CartList.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.HistoryList}
 */
proto.HistoryList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.HistoryList;
  return proto.HistoryList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.HistoryList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.HistoryList}
 */
proto.HistoryList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new ProductList_pb.ProductList;
      reader.readMessage(value,ProductList_pb.ProductList.deserializeBinaryFromReader);
      msg.setProducts(value);
      break;
    case 2:
      var value = new CartList_pb.CartList;
      reader.readMessage(value,CartList_pb.CartList.deserializeBinaryFromReader);
      msg.setCarts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.HistoryList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.HistoryList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.HistoryList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.HistoryList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProducts();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      ProductList_pb.ProductList.serializeBinaryToWriter
    );
  }
  f = message.getCarts();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      CartList_pb.CartList.serializeBinaryToWriter
    );
  }
};


/**
 * optional ProductList products = 1;
 * @return {?proto.ProductList}
 */
proto.HistoryList.prototype.getProducts = function() {
  return /** @type{?proto.ProductList} */ (
    jspb.Message.getWrapperField(this, ProductList_pb.ProductList, 1));
};


/**
 * @param {?proto.ProductList|undefined} value
 * @return {!proto.HistoryList} returns this
*/
proto.HistoryList.prototype.setProducts = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.HistoryList} returns this
 */
proto.HistoryList.prototype.clearProducts = function() {
  return this.setProducts(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.HistoryList.prototype.hasProducts = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CartList carts = 2;
 * @return {?proto.CartList}
 */
proto.HistoryList.prototype.getCarts = function() {
  return /** @type{?proto.CartList} */ (
    jspb.Message.getWrapperField(this, CartList_pb.CartList, 2));
};


/**
 * @param {?proto.CartList|undefined} value
 * @return {!proto.HistoryList} returns this
*/
proto.HistoryList.prototype.setCarts = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.HistoryList} returns this
 */
proto.HistoryList.prototype.clearCarts = function() {
  return this.setCarts(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.HistoryList.prototype.hasCarts = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto);
