// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: HistoryList.proto

//comment this for js // for join do this for all files e.g ProducList & Product etc

package protobufModel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products *ProductList `protobuf:"bytes,1,opt,name=products,proto3" json:"products,omitempty"`
	Carts    *CartList    `protobuf:"bytes,2,opt,name=carts,proto3" json:"carts,omitempty"`
}

func (x *HistoryList) Reset() {
	*x = HistoryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HistoryList_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryList) ProtoMessage() {}

func (x *HistoryList) ProtoReflect() protoreflect.Message {
	mi := &file_HistoryList_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryList.ProtoReflect.Descriptor instead.
func (*HistoryList) Descriptor() ([]byte, []int) {
	return file_HistoryList_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryList) GetProducts() *ProductList {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *HistoryList) GetCarts() *CartList {
	if x != nil {
		return x.Carts
	}
	return nil
}

var File_HistoryList_proto protoreflect.FileDescriptor

var file_HistoryList_proto_rawDesc = []byte{
	0x0a, 0x11, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x1a, 0x11, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a, 0x0b, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x05,
	0x63, 0x61, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x61, 0x72, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x63, 0x61, 0x72, 0x74, 0x73, 0x42, 0x11, 0x5a, 0x0f, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_HistoryList_proto_rawDescOnce sync.Once
	file_HistoryList_proto_rawDescData = file_HistoryList_proto_rawDesc
)

func file_HistoryList_proto_rawDescGZIP() []byte {
	file_HistoryList_proto_rawDescOnce.Do(func() {
		file_HistoryList_proto_rawDescData = protoimpl.X.CompressGZIP(file_HistoryList_proto_rawDescData)
	})
	return file_HistoryList_proto_rawDescData
}

var file_HistoryList_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_HistoryList_proto_goTypes = []interface{}{
	(*HistoryList)(nil), // 0: protobufModel.HistoryList
	(*ProductList)(nil), // 1: protobufModel.ProductList
	(*CartList)(nil),    // 2: protobufModel.CartList
}
var file_HistoryList_proto_depIdxs = []int32{
	1, // 0: protobufModel.HistoryList.products:type_name -> protobufModel.ProductList
	2, // 1: protobufModel.HistoryList.carts:type_name -> protobufModel.CartList
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_HistoryList_proto_init() }
func file_HistoryList_proto_init() {
	if File_HistoryList_proto != nil {
		return
	}
	file_ProductList_proto_init()
	file_CartList_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_HistoryList_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HistoryList_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_HistoryList_proto_goTypes,
		DependencyIndexes: file_HistoryList_proto_depIdxs,
		MessageInfos:      file_HistoryList_proto_msgTypes,
	}.Build()
	File_HistoryList_proto = out.File
	file_HistoryList_proto_rawDesc = nil
	file_HistoryList_proto_goTypes = nil
	file_HistoryList_proto_depIdxs = nil
}
